
import __ASTRO_IMAGE_IMPORT_Z1zrY7F from "./callisthenics-stories-of-support-aversion-and-love.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-01-23-performance+callisthenics%2Findex.md";
import __ASTRO_IMAGE_IMPORT_2ucx8Q from "./impression-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-01-23-performance+callisthenics%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1jW019 from "./impression-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-01-23-performance+callisthenics%2Findex.md";
import __ASTRO_IMAGE_IMPORT_nJo02 from "./poster.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-02-14-performance-ushering-in-some-alternate-egos%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1Wxf8u from "./pd-resonance-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-06-20-presentation-professional-doctrorate-arts-%2B-creative%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1U1Onh from "./pd-resonance-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-06-20-presentation-professional-doctrorate-arts-%2B-creative%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1RvoC4 from "./pd-resonance-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-06-20-presentation-professional-doctrorate-arts-%2B-creative%2Findex.md";
import __ASTRO_IMAGE_IMPORT_gVC4m from "./programme-callisthenics.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-05-10-performance-callisthenics%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Zd50dU from "./performance-callisthenics.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-05-10-performance-callisthenics%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZJATFk from "./werkconferentie-exploding-practices.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-05-16-presentation-and-panel%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1wrMH4 from "./de-tafel-van-kunst-en-methode.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-05-16-presentation-and-panel%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Zhf0jK from "./programme-performance-research-on-social-imaginaries.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-05-16-presentation-and-panel%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1g05p2 from "./in-these-circumstances.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-06-21-presentation-book-in-these-circumstances%2Findex.md";
import __ASTRO_IMAGE_IMPORT_22yhkr from "./public-rehearsal-ushering-in-some-alternate-egos.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-11-28-public-rehearsal%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1F1JI0 from "./hello-alter-ego.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-10-17-hello-alter-ego%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2heeuo from "./schedule.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2026-03-dis-seminar-3%2Findex.md";
export default new Map([["./callisthenics-stories-of-support-aversion-and-love.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-01-23-performance+callisthenics%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1zrY7F], ["./impression-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-01-23-performance+callisthenics%2Findex.md", __ASTRO_IMAGE_IMPORT_2ucx8Q], ["./impression-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-01-23-performance+callisthenics%2Findex.md", __ASTRO_IMAGE_IMPORT_1jW019], ["./poster.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-02-14-performance-ushering-in-some-alternate-egos%2Findex.md", __ASTRO_IMAGE_IMPORT_nJo02], ["./pd-resonance-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-06-20-presentation-professional-doctrorate-arts-%2B-creative%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1Wxf8u], ["./pd-resonance-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-06-20-presentation-professional-doctrorate-arts-%2B-creative%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1U1Onh], ["./pd-resonance-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-06-20-presentation-professional-doctrorate-arts-%2B-creative%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1RvoC4], ["./programme-callisthenics.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-05-10-performance-callisthenics%2Findex.md", __ASTRO_IMAGE_IMPORT_gVC4m], ["./performance-callisthenics.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-05-10-performance-callisthenics%2Findex.md", __ASTRO_IMAGE_IMPORT_Zd50dU], ["./werkconferentie-exploding-practices.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-05-16-presentation-and-panel%2Findex.md", __ASTRO_IMAGE_IMPORT_ZJATFk], ["./de-tafel-van-kunst-en-methode.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-05-16-presentation-and-panel%2Findex.md", __ASTRO_IMAGE_IMPORT_1wrMH4], ["./programme-performance-research-on-social-imaginaries.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-05-16-presentation-and-panel%2Findex.md", __ASTRO_IMAGE_IMPORT_Zhf0jK], ["./in-these-circumstances.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-06-21-presentation-book-in-these-circumstances%2Findex.md", __ASTRO_IMAGE_IMPORT_1g05p2], ["./public-rehearsal-ushering-in-some-alternate-egos.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-11-28-public-rehearsal%2Findex.md", __ASTRO_IMAGE_IMPORT_22yhkr], ["./hello-alter-ego.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2025-10-17-hello-alter-ego%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1F1JI0], ["./schedule.png?astroContentImageFlag=&importer=src%2Fcontent%2Fnews%2F2026-03-dis-seminar-3%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2heeuo]]);
		